
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Aug 31 2020 03:49:39 EDT (Aug 31 2020 07:49:39 UTC)

// Verification Directory fv/mel_puf 

module puf_template(in0, sel, out0);

input in0, sel;
output out0;
wire in0, sel;
wire out0;
wire w1,w2,w3;

INVX1 inst0 ( .A(w1), .Y(w2) );
INVX1 inst1 ( .A(w2), .Y(w1) );
INVX1 inst2 ( .A(in0), .Y(w3) );
MUX2X1 inst4 ( .A(w3), .B(w2), .S(sel), .Y(out0) );

endmodule