
// Generated by Cadence Genus(TM) Synthesis Solution 19.15-s090_1
// Generated on: Jun 21 2022 11:20:11 EDT (Jun 21 2022 15:20:11 UTC)

// Verification Directory fv/puf_nand_template 

module puf_template_inverter(in0, in1, sel, out0, out1);
  input in0, in1, sel;
  output out0, out1;
  wire in0, in1, sel;
  wire out0, out1;
  wire w0,w1,w2,w3;

  INVX1 inst1 (.A (w0), .Y (out0));
  INVX1 inst2 (.A (w1), .Y (out1));
  
  MUX2X1 inst4 ( .A(in0), .B(out1), .S(sel), .Y(w2) );
  INVX1 inst5 ( .A(w2), .Y(w0) );
  MUX2X1 inst6 ( .A(in1), .B(out0), .S(sel), .Y(w3) );
  INVX1 inst7 ( .A(w3), .Y(w1) );

endmodule

